# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('css_sprites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cssconf',
            name='id',
        ),
        migrations.AlterField(
            model_name='cssconf',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
